#!/bin/bash

TEXT_EDITOR=vi

ROLE_ACTION=$1
SERVICE=$2
INVENTORY=inventory.yaml
PAUSE_TIME=1

# COLOR VARS
CLEAR_COLOR="\033[0m"
RED_COLOR="\033[31m"
GREEN_COLOR="\033[32m"
PURPLE_COLOR='\033[0;35m'
BLUE_COLOR='\033[0;34m'

# === I.SCRIPT

function install_prepare()
{
# 1. Found service in servers list list
# if need add service add var SECTION_<YOUR_SERVICE>, and add to SECTION_ALL and to # 3. Get section by service name (see below)
SECTION_NETWORK=`ls -1 network | grep -v ".yaml"`
SECTION_MONITORING=`ls -1 monitoring | grep -v ".yaml"`
SECTION_SECURITY=`ls -1 security | grep -v ".yaml"`
LB="\n" # Line Break
SECTION_ALL=`echo -e ${SECTION_NETWORK}${LB}${SECTION_MONITORING}${LB}${SECTION_SECURITY}`

SERVICE_FOUND=false
for sections in $SECTION_ALL
do
    if [ $sections == $SERVICE ];then
        echo -en "Check Service Name: $SERVICE [$GREEN_COLOR OK $CLEAR_COLOR]\n"
        SERVICE_FOUND=true
        break
    fi
done

if [ $SERVICE_FOUND == "false" ];then
    echo -en "Check Service Name:  $SERVICE [$RED_COLOR FAIL $CLEAR_COLOR]\n"
    echo "It must be one of this services:"
    echo -e "$SECTION_ALL"
    exit 1
fi


# 2. Check actions
ROLE_ACTION_LIST="install configure restart tune"
ROLE_ACTION_FOUND=false
for action in $ROLE_ACTION_LIST
do
    if [ $action == $ROLE_ACTION ];then
        echo -en "Check Action Name: $ROLE_ACTION [$GREEN_COLOR OK $CLEAR_COLOR]\n"
        ROLE_ACTION_FOUND=true
        break
    fi
done

if [ $ROLE_ACTION_FOUND == "false" ];then
    echo -en "Check Action Name: $ROLE_ACTION [$RED_COLOR FAIL $CLEAR_COLOR]\n"
    echo "It must be one of this roles:"
    echo -e "$ROLE_ACTION_LIST"
    exit 1
fi


# 3. Get section by service name
for service_in_section in $SECTION_NETWORK
do
    if [ $service_in_section == $SERVICE ];then
        SECTION=network
        echo -en "Check Section Name: $SECTION [$GREEN_COLOR OK $CLEAR_COLOR]\n"
        break
    fi
done

for service_in_section in $SECTION_MONITORING
do
    if [ $service_in_section == $SERVICE ];then
        SECTION=monitoring
        echo -en "Check Section Name: $SECTION [$GREEN_COLOR OK $CLEAR_COLOR]\n"
        break
    fi
done

for service_in_section in $SECTION_SECURITY
do
    if [ $service_in_section == $SERVICE ];then
        SECTION=sequrity
        echo -en "Check Section Name: $SECTION [$GREEN_COLOR OK $CLEAR_COLOR]\n"
        break
    fi
done
}

# === II.COMMANDS

# 1. Run setup configs
function setup_configs()
{
    echo -e "$PURPLE_COLOR Configuring $SECTION $SERVICE... $CLEAR_COLOR"
    sleep $PAUSE_TIME
    $TEXT_EDITOR ${SECTION}/${SERVICE}/vars/main.yaml
}


# 2. Run ansible
function run_ansible()
{
    echo "$PURPLE_COLOR Start section: $SECTION action: $ROLE_ACTION service: $SERVICE $CLEAR_COLOR"
    ansible-playbook ${SECTION}/${SECTION}_main.yaml -i $INVENTORY -e "role_action=${ROLE_ACTION} role_current=${SERVICE}" --tags "${SERVICE}"
}


command() {
    case "$1" in
        install)
            install_prepare
            setup_configs
            run_ansible
            ;;
        configure)
            install_prepare
            run_ansible
            ;;
        restart)
            install_prepare
            run_ansible
            ;;
        tune)
            install_prepare
            setup_configs
            ;;
        *)
            echo ""
            echo $"Usage: $0 { install <service> | configure <service> | restart <service> } "
            echo "    $0 install <service> - install service"
            echo "    $0 configure <service> - reconfigure & restart service"
	        echo "    $0 restart <service> - restart service"
	        echo "    $0 tune <service> - setup config files for service"
            exit 1
    esac
}

command "$1"

exit 0
