---
- name: "XRDP Server"
  hosts: xrdp_server
  become: true
  # We collect facts in main.yaml (in service dir) via module setup. 
  # Otherwise, a lot of time is lost when all tasks will collect facts in this yaml file
  gather_facts: no
  roles: 
    - { role: 'xrdp', tags: 'xrdp'}


- name: "DHCP Server"
  hosts: dhcp_server
  become: true
  gather_facts: no
  roles: 
    - { role: 'dhcp', tags: 'dhcp'}


- name: "DNS Server"
  hosts: dns_server
  become: true
  gather_facts: no
  roles: 
    - { role: 'dns', tags: 'dns'}

- name: "OpenVPN Server"
  hosts: openvpn_server
  become: true
  gather_facts: no
  roles: 
    - { role: 'openvpn', tags: 'openvpn'}
