---
  #- include_vars:
  #    file: vars/vars.yaml

  - name: "Install DNS"
    ansible.builtin.package:
      name: bind
      state: present

  - name: "Enable named service"
    ansible.builtin.systemd:
      name: named
      enabled: true
