---
- name: "Prometheus - Template Main Settings File"
  ansible.builtin.template:
    src: prometheus.j2
    dest: "{{ prometheus_settings_dir }}/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart_prometheus

- name: "Prometheus - Template systemd service File"
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  notify: restart_prometheus

- name: "Prometheus - Start systemd prometheus"
  ansible.builtin.systemd:
    name: prometheus
    state: started
    daemon_reload: yes
    enabled: yes
